#!/usr/bin/env python3
"""Render games/<id>/game.toml into game_config.h and game_config.cmake.

    tools/gen_game_config.py --game-dir /abs/path/to/<game> --header OUT.h --cmake OUT.cmake

The header is what runtime/, dx/ and host/ include for every game-specific
value; the cmake fragment names the app and the image base for the build."""

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import game_config  # noqa: E402

STRINGS = (("id", "RECOMP_GAME_ID"), ("name", "RECOMP_GAME_NAME"), ("app_name", "RECOMP_APP_NAME"),
           ("bundle_id", "RECOMP_BUNDLE_ID"), ("executable", "RECOMP_EXECUTABLE"),
           ("sha256", "RECOMP_EXE_SHA256"), ("guest_root", "RECOMP_GUEST_ROOT"))
ADDRESSES = (("image_base", "RECOMP_IMAGE_BASE"), ("entry_point", "RECOMP_ENTRY_POINT"),
             ("heap_base", "RECOMP_HEAP_BASE"))


def c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_hex(value):
    return "0x%08xu" % value


def render_header(cfg):
    game = cfg["game"]
    lines = ["/* generated by tools/gen_game_config.py from %s -- do not edit */" % cfg["source"],
             "#pragma once"]
    for key, macro in STRINGS:
        lines.append("#define %s %s" % (macro, c_string(game[key])))
    for key, macro in ADDRESSES:
        lines.append("#define %s %s" % (macro, c_hex(game[key])))
    # Absolute: the developer's game lives beside game.toml, not under the kit.
    lines.append("#define RECOMP_DEVELOPER_EXE %s" % c_string(cfg["developer_exe_path"].as_posix()))
    lines.append("#define RECOMP_DEVELOPER_GAME_DIR %s" % c_string(cfg["developer_exe_path"].parent.as_posix()))
    lines.append("#define RECOMP_GAME_DIR %s" % c_string(Path(cfg["dir"]).resolve().as_posix()))
    lines.append("#define RECOMP_KIT_DIR %s" % c_string(Path(__file__).resolve().parents[1].as_posix()))
    # The on-screen keypad's starting visibility: "auto" shows it when no hardware keyboard is attached.
    lines.append("#define RECOMP_TOUCH_KEYPAD_HIDDEN %d" % (1 if cfg["touch"]["keypad"] == "hidden" else 0))
    # The mod runtime's built-in game integrations (animation clock, native
    # options menu, settings persistence, sprite view) were written against
    # Populous and hook its routines by address. Another game turns them off.
    builtin = cfg.get("mods", {}).get("builtin", "populous")
    if builtin not in ("populous", "none"):
        raise ValueError('[mods] builtin must be "populous" or "none", not %r' % builtin)
    lines.append("#define RECOMP_MODS_BUILTIN_POPULOUS %d" % (1 if builtin == "populous" else 0))
    for key, value in sorted(cfg.get("hooks", {}).items()):
        macro = "RECOMP_HOOK_" + key.upper()
        if isinstance(value, list):
            lines.append("#define %s_COUNT %d" % (macro, len(value)))
            lines.append("#define %s {%s}" % (macro, ", ".join(c_hex(v) for v in value)))
        else:
            lines.append("#define %s %s" % (macro, c_hex(value)))
    for key, entry in sorted(cfg.get("globals", {}).items()):
        macro = "RECOMP_GLOBAL_" + key.upper()
        lines.append("#define %s_ADDR %s" % (macro, c_hex(entry["addr"])))
        for field in ("size", "stride", "count"):
            if field in entry:
                lines.append("#define %s_%s %du" % (macro, field.upper(), entry[field]))
    return "\n".join(lines) + "\n"


def render_cmake(cfg):
    game = cfg["game"]
    lines = ["# generated by tools/gen_game_config.py from %s -- do not edit" % cfg["source"]]
    for key, macro in STRINGS[:5]:
        lines.append('set(%s "%s")' % (macro, game[key]))
    lines.append("set(RECOMP_IMAGE_BASE %s)" % c_hex(game["image_base"]))
    lines.append("set(RECOMP_HEAP_BASE %s)" % c_hex(game["heap_base"]))
    lines.append('set(RECOMP_DEVELOPER_GAME_DIR "%s")' % cfg["developer_exe_path"].parent.as_posix())
    lines.append('set(RECOMP_DEVELOPER_EXE "%s")' % cfg["developer_exe_path"].as_posix())
    return "\n".join(lines) + "\n"


def write_if_changed(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.is_file() or path.read_text() != text:
        path.write_text(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-dir", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--cmake", type=Path, required=True)
    args = parser.parse_args()
    cfg = game_config.load(args.game_dir)
    write_if_changed(args.header, render_header(cfg))
    write_if_changed(args.cmake, render_cmake(cfg))


if __name__ == "__main__":
    main()
